version: "3.8"
services:
  polkadot:
    container_name: polkadot
    image: chevdor/polkadot:latest
    volumes:
      - ~/polkadot-data:/data
    # ports:
    #   - "9944:9944"
    command: 'polkadot --chain polkadot --pruning="archive" --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all --name="Liquid#1"'

  sidecar:
    build: .
    ports:
      - "8080:8080"
    environment:
      SAS_SUBSTRATE_URL: http://polkadot:9933
